[package]
name = "viadkim"
version = "0.0.1"
edition = "2021"
rust-version = "1.65.0"
description = "Implementation of the DomainKeys Identified Mail (DKIM) specification"
license = "GPL-3.0-or-later"
categories = ["email"]
keywords = ["dkim", "email", "smtp"]
repository = "https://gitlab.com/glts/viadkim"

[dependencies]
base64 = "0.20.0"
bstr = { version = "1.1.0", default-features = false, features = ["std"] }
digest = { version = "0.10.6" }
ed25519 = { version = "1.5.2", features = ["alloc", "pkcs8"] }
ed25519-dalek = "1.0.1"
idna = "0.3.0"
pkcs8 = { version = "0.9.0", features = ["pem"] }
rand = "0.8.5"
rsa = "0.7.2"
sha2 = { version = "0.10.6", features = ["oid"] }
tokio = { version = "1.24.1", features = ["fs", "macros", "rt", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.37"
trust-dns-resolver = { version = "0.22.0", optional = true }

[dev-dependencies]
tracing-subscriber = "0.3.16"

[[example]]
# TODO also dkimsign; read msg from stdin for both
name = "dkimverify"
required-features = ["trust-dns-resolver"]

[[test]]
name = "basic"
required-features = ["trust-dns-resolver"]

[package.metadata.docs.rs]
all-features = true
