[package]
name = "viadkim"
version = "0.0.3"
edition = "2021"
rust-version = "1.65.0"
description = "Implementation of the DomainKeys Identified Mail (DKIM) specification"
license = "GPL-3.0-or-later"
categories = ["cryptography", "email"]
keywords = ["dkim", "email", "smtp"]
repository = "https://gitlab.com/glts/viadkim"

[dependencies]
base64ct = { version = "1.6.0", features = ["alloc"] }
bstr = { version = "1.4.0", default-features = false, features = ["std"] }
digest = "0.10.6"
ed25519-dalek = { version = "2.0.0-rc.2", features = ["pkcs8"] }
idna = "0.3.0"
pkcs8 = { version = "0.10.2", features = ["pem"] }
rsa = "0.9.0-pre.1"
sha1 = { version = "0.10.5", features = ["oid"], optional = true }
sha2 = { version = "0.10.6", features = ["oid"] }
tokio = { version = "1.26.0", features = ["fs", "macros", "rt", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.37"
trust-dns-resolver = { version = "0.22.0", optional = true }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["io-std", "io-util"] }
tracing-subscriber = "0.3.16"

[[example]]
name = "dkimverify"
required-features = ["trust-dns-resolver"]

[[test]]
name = "basic"
required-features = ["trust-dns-resolver"]

[package.metadata.docs.rs]
features = ["trust-dns-resolver"]
