[package]
name = "viadkim"
version = "0.0.1"
edition = "2021"
rust-version = "1.65.0"
description = "Implementation of the DomainKeys Identified Mail (DKIM) specification"
license = "GPL-3.0-or-later"
categories = ["email"]
keywords = ["dkim", "email", "smtp"]
repository = "https://gitlab.com/glts/viadkim"

[dependencies]
base64 = "0.20.0"
bstr = { version = "1.0.1", default-features = false, features = ["std"] }
digest = { version = "0.10.0" }
ed25519 = { version = "1.5.2", features = ["alloc", "pkcs8"] }
ed25519-dalek = "1.0.1"
idna = "0.3"
rand = "0.8"
rsa = "0.7"
sha2 = { version = "0.10.6", features = ["oid"] }
tokio = { version = "1.22.0", features = ["fs", "macros", "rt", "rt-multi-thread", "sync", "time"] }
tracing = "0.1.37"
trust-dns-resolver = { version = "0.22.0", optional = true }

pkcs8 = { version = "0.9", features = [] }

[dev-dependencies]
tracing-subscriber = "0.3.15"

[features]
# TODO should be empty:
default = ["trust-dns-resolver"]

[[example]]
name = "dkimverify"
required-features = ["trust-dns-resolver"]

[package.metadata.docs.rs]
all-features = true
